name: Airnode Application
description: Request to Join subAPI
title: "[Application]: <title>"
labels: ["application"]
assignees:
  - hujw77
body:
  - type: input
    id: airnode-xpub
    attributes:
      label: Airnode xpub address
      description: xpub address of your airnode wallet
      placeholder: ex. 0x1234...
    validations:
      required: true
  - type: input
    id: airnode-pub
    attributes:
      label: Airnode public address
      description: Public address of your airnode wallet
      placeholder: ex. 0x1234...
    validations:
      required: true
  - type: input
    id: rewards-wallet
    attributes:
      label: Your wallet for rewards
      description: Address to receive rewards
      placeholder: ex. 0x1234...
    validations:
      required: true
